staging: qcacld-3.0: fix: Fix array size mismatch in parser_api.c
Log:
kernel/msm-5.4/drivers/staging/qcacld-3.0/core/mac/src/sys/legacy/src/utils/src/parser_api.c:6177:14: error: argument 'mdie' of type 'uint8_t[3]' (aka 'unsigned char[3]') with mismatched bound [-Werror,-Warray-parameter]
                   uint8_t mdie[])
                           ^
Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: Iecb53b2e61cdfc751123807ccdd2914f74cf4da1
(cherry picked from commit 2333df88f112ad4d7bf82ca0109d67a292675995)
Signed-off-by: Madara273 <ravenhoxs@gmail.com>
Signed-off-by: Robin <hanya8493@gmail.com>